### ISSUE TITLE
Complete lack of documentation?

### ISSUE THREAD

**Issue by BryceStansfield** [JuliaPolyhedra/ConvexHull.jl#7]
Hey, so I'm scoping out this package for use in some code, but tbh the lack of documentation is making it pretty difficult since I'd rather not code something up and then find out later that I was doing something wrong or that the package doesn't do what I thought it did.

Is there any chance of adding some (even minimalistic) documentation, it'd be a huge help to anyone trying to use this code in the future. Thanks!

**Comment by blegat** [comment]
As this package uses the Polyhedra interface, so if you use it through this interface, the behavior is defined [here](https://juliapolyhedra.github.io/Polyhedra.jl/stable/index.html).

**Comment by BryceStansfield** [comment]
Ah, cool, thanks!
